### ISSUE TITLE
uninitialized constant Jwthumbs

### ISSUE THREAD

**Issue by Bite-A-Rock** [scaryguy/jwthumbs#3]
Hopefully, I am not putting this request in the wrong place...

I am absolutely new to Ruby.  I would love to use your utility.  Looks like I have all the prerequisites installed (FFMPEG, imagemagic, JWthumbs, ruby 2.1.5).

I enter 'irb' from my OSX command line and then enter 'movie = Jwthumbs::Movie.new("YOUR_VIDEO.mp4")'. At that point I get the following error.

NameError: uninitialized constant Jwthumbs
    from (irb):2
    from /usr/local/bin/irb:11:in `<main>'

I am hoping you can get me started in the right direction. Thanks!

**Comment by scaryguy** [comment]
In order to use an external gem/library inside MRI, you need to `require` it. Inside the `irb` command line, type:

``` console
 require 'jwthumbs'
```

If you'd like to use the gem inside a Ruby on Rails project, simple add it to your gemfile.

``` ruby
gem 'jwthumbs'
```

**Comment by Bite-A-Rock** [comment]
Awesome! Works great.  Sorry for the ruby ignorance and thank you for a great gem. :-)
